### ISSUE TITLE
Cached item not found during github action

### ISSUE THREAD

**Issue by jfcrenshaw** [showyourwork/showyourwork#102]
I have two trained models cached in a zenodo sandbox draft:
<img width="1157" alt="image" src="https://user-images.githubusercontent.com/41785729/170741271-93b950fe-d27f-4a6c-b420-049346baebd6.png">

Both are used in plotting scripts to make figures for [my paper](https://github.com/jfcrenshaw/pzflow-paper).

The two moons flow is found and the plot is made, but the main galaxy flow is not. During the [github action](https://github.com/jfcrenshaw/pzflow-paper/actions/runs/2397451052), I get the error

> ```
> Running user rule train_main_galaxy_flow...
> Searching remote file cache: src/data/main_galaxy_flow.pzflow.pkl...
> Required version of file not found in cache: src/data/main_galaxy_flow.pzflow.pkl.
> Cache for src/data/main_galaxy_flow.pzflow.pkl not found, and `run_cache_rules_on_ci` is set to `False`.
> ```

The corresponding rule in my [`Snakefile`](https://github.com/jfcrenshaw/pzflow-paper/blob/main/Snakefile) is
```
rule train_main_galaxy_flow:
    output:
        "src/data/main_galaxy_flow.pzflow.pkl"
    cache:
        True
    script:
        "src/scripts/train_main_galaxy_flow.py"
```

And the main galaxy flow is listed as a dependency in my [`showyourwork.yml`](https://github.com/jfcrenshaw/pzflow-paper/blob/main/showyourwork.yml):
```
dependencies:
  src/scripts/plot_two_moons.py:
    - src/data/two_moons_flow.pzflow.pkl
  src/scripts/plot_main_galaxy_corner.py:
    - src/data/main_galaxy_flow.pzflow.pkl
```

Everything runs okay on my laptop, and I've checked what I can think of, so I don't know what's going wrong. Especially since it is able to restore the two moons flow from the Zenodo Sandbox cache.
