### ISSUE TITLE
Caching with multiple outputs

### ISSUE THREAD

**Issue by arm61** [showyourwork/showyourwork#119]
I have a `Snakefile` like this 

```
rule simulation:
    output:
        ["src/data/simulation_{i}.dat"]
    cache:
        True
    script:
        "python src/scripts/simulation.py {wildcards.i}"
```

Where `i` is a variable between 0 and 5 that defines the output. But when I run this (I think) the (say) `simulation_0.dat` in the Zenodo is overwritten by (say) `simulation_1.dat` when it is created. 

Is the way round this to have a zipping rule? And do I think need an unzipping rule?

**Comment by rodluger** [comment]
This is a Snakemake limitation (see [the Snakemake docs](https://snakemake.readthedocs.io/en/stable/executing/caching.html#between-workflow-caching)):

<img width="716" alt="image" src="https://user-images.githubusercontent.com/9323819/177558439-aec4f06a-23af-4985-ac69-24619548b100.png">

Only rules with single output files can be cached, and wildcards are not supported. I'm surprised it doesn't raise an error, though, but instead seems to fail silently.

An alternative is to have the rule generate an entire _directory_, which Snakemake can cache. Your rule would look something like this:

```
rule simulation:
    output:
        directory("src/data/simulations")
    cache:
        True
    script:
        "python src/scripts/simulation.py"
```

The python script should then create the directory "src/data/simulations" and generate all the files "simulation_XX.dat" in there. Snakemake / showyourwork will then automatically zip/upload/download/unzip as needed. You do lose the wildcard functionality, though.

**Comment by arm61** [comment]
Interesting, thanks. I will close this issue as it isn't on syw

**Comment by arm61** [comment]
I think I am missing something on how to achieve this. Previously (pre-`0.3.0`), I had the following sort of thing in a `showyourwork.yml.jinja`:

```
zenodo:
    - src/data/my_data.tar.gz:
        id: 1234567
        token_name: ZENODO_TOKEN
        title: my_data
        creators:
            - McCluskey, Andrew R.
        contents:
            {% for i in [0, 1, 2, 3] -%}
            - src/data/a_result/simulation_{{i}}.dat
            {% endfor $}
            - src/data/a_result/another_file.npz
```

And this would tar everything up and push it to Zenodo. I can't really see how I can get this to occur with the `cache` stuff. I have tried adding the following in the Snakefile:

```
rule add_data:
    output:
        directory("src/data/a_result")
    cache:
        True
    shell:
        'echo "hello"'
```

Cause the files are created by >1 other scripts/rules. But this doesn't do anything, even though in my `showyourwork.yml` I have `src/data/a_result/simulation_{{i}}.dat` and `src/data/a_result/another_file.npz` as dependencies.
