### ISSUE TITLE
Pip error when building locally

### ISSUE THREAD

**Issue by jguerra-astro** [showyourwork/showyourwork#201]
Following the instructions from: https://show-your.work/en/latest/quickstart/ works, locally, up until I add the file random_numbers.py in src/scripts. running show your work after that gives the following error
```
Creating conda environment environment.yml...
Downloading and installing remote packages.
CreateCondaEnvironmentException:
Could not create conda environment from /Users/juan/software-journal-club/test-article/environment.yml:
Encountered problems while solving:
  - nothing provides requested pip 21.0.1**
```
Pushing the file to GitHub doesn't lead to any errors, and the pdf is successfully build in GitHub, so it has to be an issue with my local installation, but i'm not sure how to debug that. I haven't had any issues with pip in other conda environments.

**Comment by rodluger** [comment]
Which version of showyourwork do you have installed locally, and which version did you specify in your workflow?

**Comment by jguerra-astro** [comment]
Thanks for the quick reply!

locally its 0.3.1: 
```
> showyourwork --version
0.3.1
```
and I didn't make any edits in the workflow although this is what the build.yml is if that's what you meant:
```

name: build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build the article PDF
    concurrency: showyourwork-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build the article PDF
        id: build
        uses: showyourwork/showyourwork-action@v1
        env:
          SANDBOX_TOKEN: ${{ secrets.SANDBOX_TOKEN }}
          OVERLEAF_EMAIL: ${{ secrets.OVERLEAF_EMAIL }}
          OVERLEAF_PASSWORD: ${{ secrets.OVERLEAF_PASSWORD }}
```

**Comment by rodluger** [comment]
Can you show me your `environment.yml` file?

**Comment by jguerra-astro** [comment]
sure!
```yml 
dependencies:
  - numpy=1.19.2
  - pip=21.0.1
  - python=3.9
  - pip:
      - matplotlib==3.4.3
```

**Comment by rodluger** [comment]
Cool. I don't know why you're getting that error locally -- there's probably something fishy with either your `conda` or `mamba` installation. Other than re-installing `conda`, you could try a few things. First, try unpinning `pip` and letting `conda` choose the version for you -- does that help? If it does, try pinning `pip` it to the version it chose (`conda activate` the environment in `.snakemake/conda/XXXX` and run `pip --version`). Alternatively, you could try specifying a specific channel for `pip`, like `conda-forge::pip=21.0.1`; in fact, try doing that for everything under `dependencies`, e.g.

```yaml
dependencies:
  - conda-forge::numpy=1.19.2
  - conda-forge::pip=21.0.1
  - conda-forge::python=3.9
  - pip:
      - matplotlib==3.4.3
```
