### ISSUE TITLE
Downloading Zenodo files only if used

### ISSUE THREAD

**Issue by maxisi** [showyourwork/showyourwork#281]
I'm not sure if this is an issue or an intended feature, but it seems that Zenodo files (specified in `showyourwork.yml`) are downloaded irrespective of whether an existing cached object (in Zenodo Sandbox) would preempt the need for the original file itself.

My workflow is such that there is a script that preprocesses a relatively heavy dataset before plotting, and caches an intermediate result in Zenodo Sandbox. That intermediate file is all that is needed for the plotting script, so there should be no need to download the big dataset in the first place if the cached file is found. (I could just upload that to Zenodo, but I would still like to make the bigger dataset available.) Something like this:

```mermaid
graph TD;
    big_zenodo_file.tar.gz-->figure_prep.py;
    figure_prep.py-->cached_result.pkl;
    cached_result.pkl-->plotting_script.py
```

So, is there a way of telling _showyourwork_ to download this `big_zenodo_file.tar.gz` file from Zenodo only if the intermediate-preprocessing script `figure_prep.py` has to be run? (which itself would be triggered only if the cached file is not found)

Or is what I'm doing bad practice, and I should just change my workflow?

PS. currently I have a `showyourwork.yml` like

```
# Externally-hosted datasets, e.g. on Zenodo
datasets:
  10.XXX/zenodo.XXXXXX:
    destination: src/data
    contents:
      big_zenodo_file.tar.gz:
        one_file.hdf5:
        another_file.hdf5

dependencies:
  src/scripts/plotting_script.py:
    - src/data/cached_result.pkl
```

and a `Snakefile` like:

```
rule figprep:
    input:
        "src/data/big_zenodo_file/one_file.hdf5",
        "src/data/big_zenodo_file/another_file.hdf5",
    output:
        "src/data/cached_result.pkl"
    cache:
        True
    script: 
        "src/scripts/figure_prep.py"
```
