### ISSUE TITLE
zenodo not downloading dataset

### ISSUE THREAD

**Issue by TobiBu** [showyourwork/showyourwork#373]
Hi, I keep on getting an error with syw that one of my data files from zenodo can't be found although I think I've set up my dependency graph correctly.

from my showyourwork.yml

>dependencies:
  src/scipts/mdf_oxygen.py:
    - src/data/2.79e12..01350_halo0_total_age_fe.dat

>datasets:
  10.5281/zenodo.7928529:
    destination: src/data/
    contents:
      2.79e12..01350_halo0_total_age_fe.dat

the exact error I get is:

>User authentication for 10.5281/zenodo.7224272 is valid.
 Generating figure output: src/tex/figures/2.79e12_mdf_oxygen_gas.pdf...
Traceback (most recent call last):
  File "src/scripts/mdf_oxygen.py", line 56, in <module>
    data_main3 = pickle.load(open( paths.data / '2.79e12..01350_halo0_total_age_fe.dat','rb'))
FileNotFoundError: [Errno 2] No such file or directory: 'src/data/2.79e12..01350_halo0_total_age_fe.dat'

any ideas what goes wrong?

**Comment by dfm** [comment]
I don't know off the top of my head, but how about if you try this syntax instead:

```yaml
datasets:
  10.5281/zenodo.7928529:
    contents:
      2.79e12..01350_halo0_total_age_fe.dat: src/data/2.79e12..01350_halo0_total_age_fe.dat
```

just to make it more explicit!
