### ISSUE TITLE
Figures generated as TeX source code from a python script

### ISSUE THREAD

**Issue by HealthyPear** [showyourwork/showyourwork#445]
I would like to know if there is support for figures generated with software such as https://github.com/nschloe/tikzplotlib.

I don't think it should require anything special, but I am testing it  and I can't make it work (with a quite complex workflow, my bad - I can try to test it on something simpler in the near future).

In `ms.tex` I am doing at some point,

`\input{figures/SED.tex}`

at first launching `showyourwork build` I got,

`error: ms.tex:86: ! LaTeX Error: File 'figures/SED.tex' not found.`

which is fine I guess, as I suspect being this not a python file coupled with a `\script` command, showyourwork needs more info.

So next step I added this to my `showyourwork.yml` file,

```yaml
dependencies:
  src/tex/figures/SED.tex:
    - src/scripts/plots/scripts/make_sed.py
```

Where `make_sed.py` is a python script which depends itself on a file that should get produce by a custom rule in my `Snakefile`.

So I was expecting showyourwork complaining that the data file needed by the script cannot be found, but instead it's still saying

`error: ms.tex:86: ! LaTeX Error: File 'figures/SED.tex' not found.`

Am I making some mistake along the line? Have I hit a particular bug or missing feature?

**Comment by HealthyPear** [comment]
OK I had to do it like this (in decresing chronological order for showyourwork):

1. `\input{figures/SED.tex}`
2. define this tex file as a dependency of the main tex file in `showyourwork.yml` file
3. define a snakemake rule to tell the system that this file gets created by my python script

I don't know if this is the best practice, as the documentation does not cover this specific scenario, let me know if this should be done differently

**Comment by HealthyPear** [comment]
OK I managed to make this work with a little example in which I had only 1 rule in the Snakefile, but now with the real case scenario, which is much more complex I cannot make it work.

I still get 

```LaTeX Error: File `figures/SED.tex' not found```

In my Snakefile I have an `all` rule like this,

```yml
rule all:
    input:
        "rule_bla.done",
        "src/tex/figures/SED.tex"
```

then a series of rules which are more or less chained to each other, then at the very end the rule that creates said TeX file

```yml

# many rules chained before this one

rule make_tex_plot:
    input:
        "src/data/a_file_created_by_rule_whatever,
        "rule_whatever.done",
    output:
        "src/tex/figures/SED.tex",
    conda:
        "environment.yml"
    script:
        "src/scripts/plots/scripts/make_sed.py"
```

(this rule depends on a previous one, which depends on a previous one, and so on...)

than in the _showyourwork_ config file I have

```yaml
dependencies:
  src/tex/ms.tex:
    - src/tex/figures/SED.tex
``` 

and in the main TeX file at some point I have `\input{figures/SED.tex}`


So I would expect that this point of the TeX compilation basically triggers **all** the Snakefile workflow....

Is there a reason why this should not work?
Perhaps it doesn't recognize the `all` rule?
