### ISSUE TITLE
snakemake "all" rule and showyourwork

### ISSUE THREAD

**Issue by HealthyPear** [showyourwork/showyourwork#455]
I have defined an "all" entrypoint rule in my Snakefile.

This rule is very simple

```yaml
rule all:
    input:
        "src/data/rule_bla.done",
        "src/tex/figures/this_figure.tex"
```

Each of the input files are produced by their own rule in the same Snakefile.

In `showyourwork.yml` I define the TeX figure as a dependency of the manuscript as so,

```yaml
dependencies:
  src/tex/ms.tex:
    - src/tex/figures/this_figure.tex
```

Whenever I call `showyourwork build` I see that the "branch" of the Snakemake workflow which leads to `src/tex/figures/this_figure.tex` gets executed and the manuscript produced.
Even though `src/data/rule_bla.done` is not a direct dependency of the manuscript, I am a bit surprised to see that it doesn't gwt produced because the `all` rule should be the one that stears the entire workflow.

Is this expected behaviour?

**Comment by HealthyPear** [comment]
To force this "independent" branch to run, I have to add 

```yaml
dependencies:
  src/tex/ms.tex:
     - "src/data/rule_bla.done",
     - "src/tex/figures/this_figure.tex"
```

which seems weird to me.

I would expect _showyourwork_ to respect the `all` rule by default.

**Comment by HealthyPear** [comment]
This is kind of related to #445.

Now I am using `\variable{figures/bla.tex}` in my main manuscript.

Let's empty the `dependencies` section in `showyourwork.yml`.

Now my Snakefile looks like this:

```yaml
rule all:
    input:
        "src/data/independent_rule_output_file",
        "src/tex/figures/bla.tex",

# now many rules chained together up to some point when they branch and one branch creates `src/data/independent_rule_output_file`

rule some_data_file:
    output: "src/data/some_data_file.txt",
    # not important here how it is produced

rule make_bla_tex:
    input:
        "src/data/some_data_file.txt",
    output:
        "src/tex/figures/bla.tex",
    script:
        "src/scripts/make_bla.py"
```

Note: `make_bla.py` depends on an `io.py` module which defines a function to open `src/data/some_data_file.txt`.

What I observe is that _showyourwork_/_snakemake_ crashes while running `make_bla.py` (so _showyourwork_ goes into the `Snakefile` and sees which rule is supposed to produce `src/tex/figures/bla.tex`.

It crashes because the loading function cannot find `src/data/some_data_file.txt` even though there is a rule just above that tells snakemake how to produce it.

On top of this, as this issue reports, the `all` rule chains the whole workflow together.

The only way I find to fix this is for now is to specify in `showyourwork.yml` the dependencies like this,

```yaml
dependencies:
    src/scripts/make_bla.py:
        - src/data/some_data_file.txt
```

Which again seems weird since the snakemake workflow is defined to already chain together these 2 ingredients.
