### ISSUE TITLE
`ms_name` option does not seem to work

### ISSUE THREAD

**Issue by HealthyPear** [showyourwork/showyourwork#479]
Still working on debugging this, but maybe someone already encountered it...

```
ChildIOException:
File/directory is a child to another output:
('/Users/michele/Data/projects/my_project/.showyourwork/compile', syw__compile_setup)
('/Users/michele/Data/projects/my_project/.showyourwork/compile/aanda.pdf', syw__compile_pdf)
ChildIOException:
File/directory is a child to another output:
('/Users/michele/Data/projects/my_project/.showyourwork/compile', syw__compile_setup)
('/Users/michele/Data/projects/my_project/.showyourwork/compile/aanda.pdf', syw__compile_pdf)
```

in my `showyourwork.yml` file I have,

```yaml
# Custom file dependencies
dependencies:
  src/tex/aanda.tex:
   - src/tex/aa.cls
   - src/data/some_dir/some_file.yml

# Name of the `.tex` manuscript and corresponding `.pdf` article
ms_name: aanda
```

where `src/data/some_dir/some_file.yml` has been correctly produced while testing with

`snakemake --use-conda -c 1 --verbose -R some_rule`
