### ISSUE TITLE
Update the cookiecutter template to fix known issues #435 and #505 automatically

### ISSUE THREAD

**Issue by HealthyPear** [showyourwork/showyourwork#507]
(Premise: I never used coockiecutter)

When calling `showyourwork setup bla/bla` the CLI subcommand runs

```python
# Set up the repo
    cookiecutter(
        str(paths.showyourwork().cookiecutter),
        no_input=True,
        extra_context={
            "user": user,
            "repo": repo,
            "name": name,
            "showyourwork_version": __version__,
            "cache_sandbox_doi": cache_sandbox_doi,
            "overleaf_id": overleaf_id,
            "year": time.localtime().tm_year,
            "action_spec": action_spec,
        },
        overwrite_if_exists=True,
    )
```

then in the template of e.g. the build workflow

```yaml
     - name: Build the article PDF
        id: build
        uses: showyourwork/showyourwork-action@v1
        {%- if cookiecutter.action_spec %}
        with:
          showyourwork-spec: {{ cookiecutter.action_spec }}{% endif %}
        env:
          SANDBOX_TOKEN: ${{ "{{" }} secrets.SANDBOX_TOKEN {{ "}}" }}
          OVERLEAF_TOKEN: ${{ "{{" }} secrets.OVERLEAF_TOKEN {{ "}}" }}
```

which results always in

```yaml
     - name: Build the article PDF
        id: build
        uses: showyourwork/showyourwork-action@v1
        env:
          SANDBOX_TOKEN: ${{ secrets.SANDBOX_TOKEN }}
          OVERLEAF_TOKEN: ${{ secrets.OVERLEAF_TOKEN }}
```

whereas I would expect something like

```yaml
     - name: Build the article PDF
        id: build
       with:
           showyourwork-spec: 0.4.4.dev53+g8e3f5df.d20241022 # or some other dev version
        uses: showyourwork/showyourwork-action@v1
        env:
          SANDBOX_TOKEN: ${{ secrets.SANDBOX_TOKEN }}
          OVERLEAF_TOKEN: ${{ secrets.OVERLEAF_TOKEN }}
```
