### ISSUE TITLE
Out-of-memory errors when caching

### ISSUE THREAD

**Issue by rodluger** [showyourwork/showyourwork#77]
_This issue was first raised in #35 by @arm61._

By default, the GitHub Action attempts to cache everything in the ``src/`` directory. It seems that if there are very large datasets (many GB), this can lead to memory errors that crash the workflow build.

To circumvent this, I added the option ``article-cache-exclude`` to the ``.github/workflows/showyourwork.yml`` config file, which should be used as follows:

```yaml
- name: Build the article PDF
  id: build
  uses: ./showyourwork/showyourwork-action
  with:
    article-cache-exclude: |
      src/data/foo.dat
      **/*.npz
```

In this example, the file ``src/data/foo.dat`` and anything with the extension ``.npz`` will not be cached. Users will have to decide (via trial-and-error) which files they need to exclude from the cache, balancing their size and how long it takes to generate/download them on CI.

@arm61 Can you give this a spin (pull from ``main`` to get this functionality) and let me know if it helps with your issues? I'd recommend bumping the ``article-cache-number`` to a never-before-used value to ensure you don't have large vestigial files lurking in the cache. Thanks!
