### ISSUE TITLE
Feature request: remake figures and rebuild manuscript when matplotlibrc is changed

### ISSUE THREAD

**Issue by jfcrenshaw** [showyourwork/showyourwork#98]

**Comment by rodluger** [comment]
You should be able to enforce this by specifying `matplotlibrc` as a dependency of the manuscript in `showyourwork.yml`:

```yaml
dependencies:
  src/tex/ms.tex:
    - src/scripts/matplotlibrc
```

I could make this the default behavior, but I don't necessarily want showyourwork to _require_ the presence of that file (since in principle other programming languages are supported as well). Does my suggestion above work for you, or do you think this should be applied by default?
